import { NextRequest, NextResponse } from "next/server";
import { getSupabaseServerClient } from "@/lib/supabase";
import { safeGenerateContent } from "@/lib/gemini";

export async function POST(request: NextRequest) {
  try {
    const { resumeId, existingResumeText, mode = "rewrite_entire", additionalData = "" } = await request.json();

    if (!existingResumeText || !existingResumeText.trim()) {
      return NextResponse.json({ error: "The resume text content is empty. Please ensure it is parsed correctly." }, { status: 400 });
    }

    const authHeader = request.headers.get("Authorization");
    const supabase = getSupabaseServerClient(authHeader);

    let userId = "";

    // If resumeId is provided, verify ownership first
    if (resumeId) {
      const { data: resume, error: resumeError } = await supabase
        .from("resumes")
        .select("id, user_id")
        .eq("id", resumeId)
        .single();

      if (resumeError || !resume) {
        return NextResponse.json({ error: "Resume not found or access denied" }, { status: 404 });
      }
      userId = resume.user_id;
    }

    let instruction = "";
    switch (mode) {
      case "improve_summary":
        instruction = "Rewrite the professional summary section to make it highly engaging, professional, and optimized for ATS keywords. Emphasize career trajectory and core competencies.";
        break;
      case "improve_experience":
        instruction = "Strengthen the work experience descriptions. Emphasize key responsibilities, achievements, and results, using strong action verbs.";
        break;
      case "improve_projects":
        instruction = "Improve the project descriptions. Detail technical choices, technologies used, problems solved, and clear quantifiable outcomes.";
        break;
      case "improve_skills":
        instruction = "Optimize the technical and soft skills lists. Group them logically (e.g., Languages, Frameworks, Developer Tools) and format them professionally.";
        break;
      case "add_ats_keywords":
        instruction = `Inject relevant industry-standard ATS keywords and technologies into the resume text (especially: ${additionalData || "industry matching skills"}). Ensure the additions flow naturally and don't look like keyword stuffing.`;
        break;
      case "make_ats_friendly":
        instruction = "Reformat and adjust the resume text layout/descriptions to be highly compatible with Applicant Tracking Systems (ATS). Remove complex layouts, and ensure standard headings are used.";
        break;
      case "make_recruiter_friendly":
        instruction = "Rewrite the resume content to make it highly appealing to human recruiters. Emphasize leadership, growth, ownership, and clear business outcomes.";
        break;
      case "reduce_length":
        instruction = "Condense the resume text. Remove fluff and overly wordy descriptions while preserving all key achievements, technical skills, and essential work history.";
        break;
      case "increase_impact":
        instruction = "Strengthen the phrasing throughout the resume to increase impact. Replace weak/passive descriptions (e.g., 'assisted with', 'responsible for') with bold, success-oriented statements.";
        break;
      case "fix_grammar":
        instruction = "Review and edit the resume to fix any spelling, grammar, punctuation, and stylistic inconsistencies, keeping the professional tone intact.";
        break;
      case "generate_achievement_statements":
        instruction = "Formulate quantifiable achievement statements based on the experience descriptions (e.g., mentioning percentages, time savings, metrics, or scale). Ensure every major work history point has a metric.";
        break;
      case "generate_star_bullet_points":
        instruction = "Rewrite the experience bullet points to strictly follow the STAR method (Situation, Task, Action, Result). Make sure each bullet has a clear action and measurable result.";
        break;
      case "rewrite_entire":
      default:
        instruction = "Enhance and rewrite the entire resume. Optimize it for ATS scanning, strengthen descriptions, inject relevant keywords, and format it in clean markdown structure.";
        break;
    }

    const prompt = `
You are an expert ATS Resume Improver.
Your task: ${instruction}

Enhance the following resume based on these instructions. Maintain all original information (name, contacts, dates, locations, credentials) but rewrite the content to achieve the goal.

Input Resume:
"""
${existingResumeText}
"""

Output ONLY the improved formatted markdown resume. Do not include markdown code block wrappers (\`\`\`).
`;

    const textResponse = await safeGenerateContent(prompt);

    if (!textResponse || !textResponse.trim()) {
      throw new Error("Empty response generated by Gemini AI");
    }

    // Save to database if resumeId is provided
    if (resumeId) {
      const { error: updateError } = await supabase
        .from("resumes")
        .update({
          improved_content: textResponse,
          updated_at: new Date().toISOString()
        })
        .eq("id", resumeId);

      if (updateError) {
        throw updateError;
      }

      // Add to resume_history
      await supabase.from("resume_history" as any).insert({
        user_id: userId,
        resume_id: resumeId,
        action: "AI Optimize",
        description: `Improved resume using AI (Mode: ${mode})`
      });

      // Add to resume_logs
      await supabase.from("resume_logs" as any).insert({
        user_id: userId,
        resume_id: resumeId,
        message: `Successfully executed AI improvement with mode: ${mode}`,
        log_type: "info",
        details: { mode }
      });
    }

    return NextResponse.json({ improved_resume: textResponse });
  } catch (error: any) {
    console.error("Error improving resume:", error);
    return NextResponse.json({ error: error.message || "Failed to improve resume" }, { status: 500 });
  }
}
